/**
 * Curated catalog of Qur'anic du'ās (supplications) keyed by intent.
 *
 * Sources:
 *  - The Qur'an itself (every verse beginning with rabbanā, rabbi, allāhumma…)
 *  - Ḥiṣn al-Muslim by Saʿīd al-Qaḥṭānī
 *  - al-Adhkār by an-Nawawī
 *  - Ibn Kathīr's tafsīr notes on du'ā verses
 *
 * Each entry has rich `intents[]` for keyword matching, and short
 * `context` / `hadith` notes the player can read aloud as an intro.
 */

export type DuaCategory =
  | "hardship"
  | "wish"
  | "provision"
  | "protection"
  | "forgiveness"
  | "guidance"
  | "anxiety"
  | "family"
  | "parents"
  | "knowledge"
  | "travel"
  | "hereafter"
  | "victory"
  | "healing"
  | "gratitude"
  | "general";

export type DuaEntry = {
  id: string;
  category: DuaCategory;
  title: string;
  surah: number;
  start: number;
  end: number;
  intents: string[];
  context: string;
  hadith?: string;
  reciter?: "alafasy" | "abdulbasit" | "husary" | "minshawi" | "sudais";
};

export const DUAS: DuaEntry[] = [
  // ─── HARDSHIP & DISTRESS ──────────────────────────────────────────────────
  {
    id: "yunus-distress",
    category: "hardship",
    title: "Duʿā of Yūnus — relief from distress",
    surah: 21, start: 87, end: 87,
    intents: ["distress","trapped","desperate","no way out","hopeless","stuck","overwhelmed","crisis","emergency","cannot escape","oppressed","relief from hardship","drowning","suffocating","darkness","alone in trouble","prison","jail","calamity"],
    context: "Recited by Prophet Yūnus ﷺ from the depths of the whale's belly, in three layers of darkness.",
    hadith: "The Prophet ﷺ said: No Muslim ever recites this duʿā for any matter except that Allah responds to him. (Tirmidhī)",
    reciter: "minshawi",
  },
  {
    id: "ayyub-affliction",
    category: "hardship",
    title: "Duʿā of Ayyūb — long affliction",
    surah: 21, start: 83, end: 84,
    intents: ["long suffering","chronic illness","prolonged hardship","afflicted","tested for years","losing patience","worn down","sustained trial","i have suffered enough","unending pain","losing hope after long wait"],
    context: "Recited by Prophet Ayyūb ﷺ after years of illness and loss, with utmost adab — never complaining, only acknowledging mercy.",
    reciter: "minshawi",
  },
  {
    id: "ash-sharh-ease",
    category: "hardship",
    title: "Sūrat ash-Sharḥ — with hardship comes ease",
    surah: 94, start: 1, end: 8,
    intents: ["hardship","difficulty","stress","heaviness","burden of life","need ease","tired","exhausted","weight of life","heavy chest","need encouragement","reassurance","keep going","relief is near"],
    context: "Allah reminds the Prophet ﷺ — and every believer — that with every difficulty there is ease. Repeated twice for emphasis.",
    reciter: "alafasy",
  },
  {
    id: "yaqub-grief",
    category: "hardship",
    title: "Duʿā of Yaʿqūb — pouring grief to Allah",
    surah: 12, start: 86, end: 86,
    intents: ["grief","sorrow","sadness","loss of loved one","missing someone","weeping","heartbroken","cant stop crying","crying alone","complain only to Allah","mourning","bereavement","lost child"],
    context: "Spoken by Yaʿqūb ﷺ after losing Yūsuf — 'I only complain of my suffering and grief to Allah.' A model for venting only to Allah.",
    reciter: "minshawi",
  },
  {
    id: "baqarah-burden",
    category: "hardship",
    title: "Last verses of al-Baqarah — bear no burden beyond capacity",
    surah: 2, start: 285, end: 286,
    intents: ["overwhelmed","cant cope","too much to handle","my burden is too heavy","feel like im breaking","at my limit","need divine help","forgive my mistakes and victory","comprehensive duʿā","general protection"],
    context: "The closing duʿā of Sūrat al-Baqarah. The Prophet ﷺ said whoever recites these two verses at night, they will suffice him.",
    hadith: "Whoever recites the last two verses of al-Baqarah at night, they will suffice him. (Bukhārī, Muslim)",
    reciter: "sudais",
  },
  {
    id: "tawbah-trust",
    category: "hardship",
    title: "Sufficient is Allah",
    surah: 9, start: 129, end: 129,
    intents: ["allah is enough","trust in allah","tawakkul","i feel alone","abandoned","betrayed","let down by people","everyone left me","need divine reliance","Hasbiyallah"],
    context: "'Sufficient for me is Allah; there is no deity except Him. Upon Him I rely, and He is the Lord of the Mighty Throne.'",
    hadith: "Whoever says this seven times in morning and evening, Allah will suffice him for whatever worries him. (Abū Dāwūd)",
    reciter: "husary",
  },
  {
    id: "ali-imran-sufficient",
    category: "hardship",
    title: "Ḥasbunallāh — Allah suffices us",
    surah: 3, start: 173, end: 174,
    intents: ["fear of enemies","threatened","intimidated","afraid of people","under attack","trust allah against odds","need courage","standing alone","outnumbered"],
    context: "Said by Ibrāhīm ﷺ in the fire, and by the Prophet Muḥammad ﷺ at Uḥud — 'Sufficient for us is Allah, and He is the best Disposer of affairs.'",
    reciter: "sudais",
  },
  {
    id: "duha-not-forsaken",
    category: "hardship",
    title: "Sūrat aḍ-Ḍuḥā — your Lord has not forsaken you",
    surah: 93, start: 1, end: 11,
    intents: ["feel forsaken","feel forgotten by allah","spiritual dryness","no progress","feel abandoned","far from allah","my prayers feel unanswered","reassurance","i matter","remembered by allah"],
    context: "Revealed when revelation paused and the Prophet ﷺ feared Allah was displeased. Allah swore by morning light: He has not forsaken you.",
    reciter: "alafasy",
  },
  {
    id: "inshirah-companion",
    category: "hardship",
    title: "Sūrat al-Inshirāḥ — expansion of the chest",
    surah: 94, start: 1, end: 8,
    intents: ["heavy chest","tightness in heart","cant breathe","need expansion","spiritual burden lifted","feeling weighed down"],
    context: "Echoes the duʿā of Mūsā 'expand for me my chest.' Companion sūrah to aḍ-Ḍuḥā.",
    reciter: "alafasy",
  },

  // ─── WISH / SPECIFIC NEEDS ────────────────────────────────────────────────
  {
    id: "musa-need",
    category: "wish",
    title: "Duʿā of Mūsā — in need of any good",
    surah: 28, start: 24, end: 24,
    intents: ["i have a need","make my wish come true","want something","desire","specific request","unmet need","poor and asking","new opportunity","new beginning","hoping","wishing","i need help","fulfill my wish"],
    context: "Said by Mūsā ﷺ in Madyan — exiled, hungry, having just helped two women water their flock. 'My Lord, I am, for whatever good You send down to me, in need.'",
    hadith: "Allah answered him with safety, marriage, and prophethood — all from this single sentence.",
    reciter: "alafasy",
  },
  {
    id: "zakariya-child-imran",
    category: "wish",
    title: "Duʿā of Zakariyyā for offspring",
    surah: 3, start: 38, end: 38,
    intents: ["want a child","infertility","trying to conceive","barren","ivf","children of my own","good offspring","righteous child"],
    context: "Said by Zakariyyā ﷺ when he saw the unseasonal provision Allah gave Maryam — and in old age was granted Yaḥyā.",
    reciter: "minshawi",
  },
  {
    id: "zakariya-child-maryam",
    category: "wish",
    title: "Duʿā of Zakariyyā — quietly, in old age",
    surah: 19, start: 4, end: 6,
    intents: ["old age and no child","late in life duʿā","quiet duʿā","whispered prayer","never been disappointed by allah","intimate prayer","secret hopes"],
    context: "Spoken in a whisper, in old age, with white hair. A model that Allah hears even silent du'ās.",
    reciter: "minshawi",
  },
  {
    id: "ibrahim-righteous-son",
    category: "wish",
    title: "Duʿā of Ibrāhīm for a righteous son",
    surah: 37, start: 100, end: 100,
    intents: ["righteous offspring","good son or daughter","duʿā for child to be pious","raise good kids"],
    context: "'My Lord, grant me [a child] from among the righteous.' Allah responded with Ismāʿīl ﷺ.",
    reciter: "alafasy",
  },
  {
    id: "kahf-mercy",
    category: "wish",
    title: "Duʿā of the Cave",
    surah: 18, start: 10, end: 10,
    intents: ["seeking refuge","need shelter","persecuted","fleeing trouble","hiding from harm","need a way forward","right course of action","clarity in confusion"],
    context: "Said by the youths of the cave when they fled persecution — 'Our Lord, grant us mercy from Yourself, and prepare for us right guidance from our affair.'",
    reciter: "alafasy",
  },
  {
    id: "anbiya-zakariya",
    category: "wish",
    title: "Duʿā of Zakariyyā — do not leave me alone",
    surah: 21, start: 89, end: 89,
    intents: ["no heir","no family","fear of dying alone","want a legacy","loneliness in old age","childless"],
    context: "'My Lord, do not leave me alone, while You are the best of inheritors.'",
    reciter: "minshawi",
  },

  // ─── PROVISION (rizq) ─────────────────────────────────────────────────────
  {
    id: "talaq-way-out",
    category: "provision",
    title: "A way out and provision from where one doesn't expect",
    surah: 65, start: 2, end: 3,
    intents: ["financial trouble","debt","unemployed","need rizq","need a job","money problem","cant pay bills","unexpected provision","barakah","income","trust allah for sustenance"],
    context: "'Whoever fears Allah, He makes for him a way out, and provides from where he does not expect.' A promise tied to taqwā.",
    reciter: "sudais",
  },
  {
    id: "isa-table",
    category: "provision",
    title: "Duʿā of ʿĪsā for the heavenly table",
    surah: 5, start: 114, end: 114,
    intents: ["asking for sustenance","food","need provision","celebration meal","feeding family","blessing in food"],
    context: "'O Allah, our Lord, send down to us a table from the heaven to be a festival for us… and provide for us, and You are the best of providers.'",
    reciter: "alafasy",
  },
  {
    id: "quraysh-feed",
    category: "provision",
    title: "Sūrat Quraysh — Lord of this House",
    surah: 106, start: 1, end: 4,
    intents: ["protection from hunger","protection from fear","safety and food","household provision","traveling for trade","business duʿā"],
    context: "Allah reminds Quraysh of His twin gifts: feeding them from hunger and securing them from fear. Recited for both barakah and safety.",
    reciter: "alafasy",
  },
  {
    id: "ibrahim-fruits",
    category: "provision",
    title: "Duʿā of Ibrāhīm for Makkah's provision",
    surah: 14, start: 37, end: 37,
    intents: ["asking for produce and rizq","family in a hard place","duʿā for a city","barakah in a place","my children need food","new home blessing"],
    context: "Said by Ibrāhīm ﷺ in the barren valley of Makkah — and Allah caused fruits of every land to be brought there.",
    reciter: "abdulbasit",
  },
  {
    id: "waqiah-provision",
    category: "provision",
    title: "Sūrat al-Wāqiʿah — the recompense",
    surah: 56, start: 1, end: 96,
    intents: ["nightly recitation for rizq","read for provision","hardship in livelihood","poverty","traditional rizq surah"],
    context: "It is reported that whoever recites Sūrat al-Wāqiʿah every night will not be touched by poverty. (Tradition; ḥadīth has scholarly discussion.)",
    reciter: "abdulbasit",
  },

  // ─── PROTECTION ───────────────────────────────────────────────────────────
  {
    id: "al-falaq",
    category: "protection",
    title: "Sūrat al-Falaq — refuge in the Lord of daybreak",
    surah: 113, start: 1, end: 5,
    intents: ["evil eye","jealousy","envy","witchcraft","sihr","jinn","dark of night","nightmares","feel watched","negative energy","protection from harm"],
    context: "One of the al-Muʿawwidhatān (the two refuges). Recited morning and evening, before sleep, after every prayer.",
    hadith: "Recite these (113 & 114), three times in morning and evening — they suffice you against all things. (Abū Dāwūd, Tirmidhī)",
    reciter: "alafasy",
  },
  {
    id: "an-nas",
    category: "protection",
    title: "Sūrat an-Nās — refuge in the Lord of mankind",
    surah: 114, start: 1, end: 6,
    intents: ["whispers in the heart","intrusive thoughts","waswas","shaytan attacks","doubt","spiritual unease","protection from people","social harm","nightmares"],
    context: "The closing companion of al-Falaq — protection from the lurking whisperer in the breasts of mankind and jinn.",
    reciter: "alafasy",
  },
  {
    id: "ayat-kursi",
    category: "protection",
    title: "Āyat al-Kursī — the verse of the Throne",
    surah: 2, start: 255, end: 255,
    intents: ["bedtime protection","before sleep","greatest verse","comprehensive shield","general protection","leaving home","entering home","fortress"],
    context: "The greatest verse of the Qur'an. Whoever recites it after each prayer, nothing prevents him from Paradise except death.",
    hadith: "Whoever recites Āyat al-Kursī when going to sleep — Allah appoints a guardian over him; no shayṭān comes near him until morning. (Bukhārī)",
    reciter: "sudais",
  },
  {
    id: "last-imran",
    category: "protection",
    title: "Last verses of Āl ʿImrān — reflection at night",
    surah: 3, start: 190, end: 200,
    intents: ["sleeplessness","reflection","awe of creation","standing in night prayer","tahajjud","contemplation","look at the sky"],
    context: "Revealed when the Prophet ﷺ wept the whole night. He said: woe to whoever recites these and does not reflect on them.",
    reciter: "abdulbasit",
  },
  {
    id: "muminun-shaytan",
    category: "protection",
    title: "Refuge from the whispers of devils",
    surah: 23, start: 97, end: 98,
    intents: ["shaytan whispers","temptation","bad thoughts","intrusive thoughts","tempted to sin","keep me firm","protect my heart"],
    context: "'My Lord, I seek refuge in You from the suggestions of the devils, and I seek refuge in You, my Lord, lest they be present with me.'",
    reciter: "husary",
  },
  {
    id: "fussilat-anger",
    category: "protection",
    title: "When Shayṭān provokes you — seek refuge",
    surah: 41, start: 36, end: 36,
    intents: ["anger","rage","about to lash out","control my temper","road rage","argument","conflict","losing my cool"],
    context: "'And if there comes to you a suggestion from Satan, then seek refuge in Allah. Indeed, He is the Hearing, the Knowing.'",
    reciter: "husary",
  },
  {
    id: "araf-pride",
    category: "protection",
    title: "Refuge from one's own ego",
    surah: 7, start: 200, end: 201,
    intents: ["pride","arrogance","ego","showing off","riya","self-conceit","spiritual pride","need humility"],
    context: "'When the God-fearing are touched by a thought from Satan, they remember [Allah], and at once they have insight.'",
    reciter: "husary",
  },

  // ─── FORGIVENESS & REPENTANCE ─────────────────────────────────────────────
  {
    id: "adam-eve",
    category: "forgiveness",
    title: "Duʿā of Ādam and Ḥawwāʾ",
    surah: 7, start: 23, end: 23,
    intents: ["i have sinned","wronged myself","need forgiveness","feel guilty","ashamed","slipped up","first repentance","starting over","i made a mistake"],
    context: "The first du'ā of repentance ever uttered by humankind. 'Our Lord, we have wronged ourselves; if You do not forgive us and have mercy upon us, we will surely be among the losers.'",
    reciter: "minshawi",
  },
  {
    id: "musa-self-wrong",
    category: "forgiveness",
    title: "Duʿā of Mūsā after his mistake",
    surah: 28, start: 16, end: 16,
    intents: ["accidental harm","unintended sin","caused damage","hurt someone unintentionally","quick repentance","instant tawbah"],
    context: "Mūsā ﷺ, after striking the Egyptian, said immediately: 'My Lord, indeed I have wronged myself, so forgive me.' And He forgave him.",
    reciter: "minshawi",
  },
  {
    id: "muminun-mercy",
    category: "forgiveness",
    title: "Closing of al-Muʾminūn",
    surah: 23, start: 118, end: 118,
    intents: ["forgive me","have mercy","best forgiver","final duʿā","general repentance"],
    context: "'My Lord, forgive and have mercy, and You are the best of the merciful.'",
    reciter: "alafasy",
  },
  {
    id: "ali-imran-firm",
    category: "forgiveness",
    title: "Duʿā of those of understanding",
    surah: 3, start: 147, end: 147,
    intents: ["forgive my excesses","cleanse my deeds","stand firm","victory over myself","steadfast against my sins","rescue from defeat"],
    context: "Spoken by sincere believers in battle: 'Our Lord, forgive us our sins and excess, plant our feet firmly, and give us victory over the disbelieving people.'",
    reciter: "sudais",
  },
  {
    id: "ali-imran-believed",
    category: "forgiveness",
    title: "We have believed, so forgive us",
    surah: 3, start: 16, end: 17,
    intents: ["new in faith","just embraced islam","tawbah","forgive and save from fire","duʿā at suḥūr","pre-dawn duʿā"],
    context: "Allah praises those 'who say: Our Lord, indeed we have believed, so forgive us our sins and protect us from the fire.' Recited especially in the last third of night.",
    reciter: "abdulbasit",
  },
  {
    id: "nuh-forgive-parents",
    category: "forgiveness",
    title: "Duʿā of Nūḥ — for self, parents, and believers",
    surah: 71, start: 28, end: 28,
    intents: ["forgive me my parents and family","comprehensive forgiveness","duʿā for muslims","whole community","my parents who passed"],
    context: "'My Lord, forgive me and my parents and whoever enters my house a believer, and the believing men and women.'",
    reciter: "alafasy",
  },
  {
    id: "ibrahim-judgement",
    category: "forgiveness",
    title: "Forgiveness on the Day of Reckoning",
    surah: 14, start: 41, end: 41,
    intents: ["scared of qiyamah","forgive me on the day of judgement","my parents on judgement day","reckoning"],
    context: "'Our Lord, forgive me and my parents and the believers the Day the account is established.'",
    reciter: "alafasy",
  },
  {
    id: "hud-nuh-knowledge",
    category: "forgiveness",
    title: "Nūḥ — refuge from asking what one shouldn't",
    surah: 11, start: 47, end: 47,
    intents: ["asked something i shouldnt","spoke without knowledge","retract my words","took back my duʿā","regret what i said","ignorant prayer"],
    context: "Said by Nūḥ ﷺ after asking after his disbelieving son: 'My Lord, I seek refuge in You from asking that of which I have no knowledge.'",
    reciter: "minshawi",
  },

  // ─── GUIDANCE & STEADFASTNESS ─────────────────────────────────────────────
  {
    id: "fatihah",
    category: "guidance",
    title: "Sūrat al-Fātiḥah — guide us to the straight path",
    surah: 1, start: 1, end: 7,
    intents: ["guidance","right path","sirat","need direction","confused","lost","major decision","istikhārah","help me choose","which way","crossroads"],
    context: "The Mother of the Book. Recited 17 times daily in obligatory prayers. The most repeated du'ā in the universe.",
    reciter: "sudais",
  },
  {
    id: "ali-imran-firm-heart",
    category: "guidance",
    title: "Do not let our hearts deviate",
    surah: 3, start: 8, end: 9,
    intents: ["fear of losing iman","my faith is wavering","keep me firm","istiqamah","heart turning away","need steadfastness","doubts"],
    context: "'Our Lord, let not our hearts deviate after You have guided us, and grant us from Yourself mercy. Indeed, You are the Bestower.'",
    reciter: "alafasy",
  },
  {
    id: "kahf-righteous",
    category: "guidance",
    title: "Mercy and a way forward — youths of the cave",
    surah: 18, start: 10, end: 10,
    intents: ["need clarity","next step in life","major life decision","find my path","starting fresh","stepping out in faith"],
    context: "'Our Lord, grant us mercy from Yourself, and prepare for us, from our affair, right guidance.'",
    reciter: "alafasy",
  },
  {
    id: "araf-judge",
    category: "guidance",
    title: "Decide between us in truth",
    surah: 7, start: 89, end: 89,
    intents: ["unfair situation","need justice","wronged by others","conflict resolution","help me see the truth","resolve a dispute"],
    context: "Shuʿayb ﷺ to his people: 'Our Lord, decide between us and our people in truth, and You are the best of those who give decision.'",
    reciter: "husary",
  },
  {
    id: "araf-patience-die-muslim",
    category: "guidance",
    title: "Pour upon us patience and let us die submitting",
    surah: 7, start: 126, end: 126,
    intents: ["asking for patience","sabr","facing torture","persecuted for faith","die as a muslim","steadfastness in trial"],
    context: "Said by the magicians of Pharaoh after they believed and were threatened with crucifixion.",
    reciter: "minshawi",
  },
  {
    id: "yunus-trust",
    category: "guidance",
    title: "Upon Allah we have relied — do not make us a trial",
    surah: 10, start: 85, end: 86,
    intents: ["dont let me be a means for the wrong to harm me","trust in allah","not be tested through enemies","tawakkul","under hostile authority"],
    context: "'Upon Allah we have relied. Our Lord, make us not [objects of] trial for the wrongdoing people, and save us by Your mercy.'",
    reciter: "alafasy",
  },
  {
    id: "ali-imran-witness",
    category: "guidance",
    title: "We have believed in what You revealed",
    surah: 3, start: 53, end: 53,
    intents: ["affirming faith","witnessing truth","new revelation in life","clarity arrived","grateful for guidance"],
    context: "'Our Lord, we have believed in what You revealed and have followed the messenger, so register us among the witnesses.'",
    reciter: "abdulbasit",
  },

  // ─── ANXIETY, FEAR, PUBLIC SPEAKING ───────────────────────────────────────
  {
    id: "musa-chest-tongue",
    category: "anxiety",
    title: "Duʿā of Mūsā — expand my chest, ease my tongue",
    surah: 20, start: 25, end: 28,
    intents: ["anxiety","panic attack","public speaking","stage fright","interview","difficult conversation","hard task ahead","cant find words","stutter","speech difficulty","fear of confrontation","big presentation","exam","viva","important meeting"],
    context: "Said by Mūsā ﷺ before confronting Pharaoh — the most quoted duʿā for any moment of high pressure or hard speech.",
    reciter: "minshawi",
  },
  {
    id: "asiya-protection",
    category: "anxiety",
    title: "Duʿā of Āsiyah — house in Paradise",
    surah: 66, start: 11, end: 11,
    intents: ["abuse","trapped in toxic relationship","domestic violence","oppressive household","i need rescue from this place","spiritual liberation","oppressed wife"],
    context: "Said by Āsiyah, wife of Pharaoh — 'My Lord, build for me, near You, a house in Paradise, and save me from Pharaoh and his deeds, and save me from the wrongdoing people.'",
    reciter: "minshawi",
  },
  {
    id: "shuara-resurrection",
    category: "anxiety",
    title: "Duʿā of Ibrāhīm on the Day of Recompense",
    surah: 26, start: 83, end: 89,
    intents: ["fear of death","afraid of qiyamah","fear my legacy","day of resurrection","sound heart","qalb saleem","what will i face","die well"],
    context: "Ibrāhīm ﷺ asks for wisdom, righteous companions, an honorable legacy of truth, and a 'sound heart' on the Day none will benefit but that.",
    reciter: "abdulbasit",
  },
  {
    id: "muminun-fear",
    category: "anxiety",
    title: "Hearts trembling — those who give in fear",
    surah: 23, start: 57, end: 61,
    intents: ["fear of allah","khashya","worry about my deeds","anxiety about acceptance","is my prayer accepted","scared my deeds wont be enough"],
    context: "Praising those whose hearts tremble even as they give and worship — afraid their deeds won't be accepted.",
    reciter: "husary",
  },

  // ─── FAMILY (spouse / children) ───────────────────────────────────────────
  {
    id: "furqan-imam",
    category: "family",
    title: "Comfort of the eyes from spouses and offspring",
    surah: 25, start: 74, end: 74,
    intents: ["marriage","spouse","wife","husband","children","family","leadership of the righteous","good home","make my family pious","duʿā for my kids"],
    context: "'Our Lord, grant us from our wives and offspring comfort to our eyes, and make us imāms for the righteous.'",
    reciter: "alafasy",
  },
  {
    id: "ahkaf-thirty",
    category: "family",
    title: "Forty years — gratitude and righteous offspring",
    surah: 46, start: 15, end: 15,
    intents: ["turning forty","midlife reflection","grateful for parents","want righteous descendants","duʿā at maturity","duʿā for unborn child","praying for child in womb"],
    context: "Recited especially when reaching forty: 'My Lord, enable me to be grateful for Your favor… and make righteous for me my offspring.'",
    reciter: "abdulbasit",
  },
  {
    id: "ibrahim-prayer-offspring",
    category: "family",
    title: "Duʿā of Ibrāhīm — establishers of prayer",
    surah: 14, start: 40, end: 40,
    intents: ["my children pray","family that prays","duʿā for descendants to be muslim","keep islam in my family","children to love prayer"],
    context: "'My Lord, make me an establisher of prayer, and many from my descendants. Our Lord, and accept my supplication.'",
    reciter: "alafasy",
  },
  {
    id: "nuh-son",
    category: "family",
    title: "Nūḥ pleading for his son",
    surah: 11, start: 45, end: 47,
    intents: ["wayward child","child has left islam","son in trouble","cant save my child","emotional plea for offspring","loved one going astray"],
    context: "Nūḥ ﷺ pleaded for his son even as the flood took him — and was taught the limits of family connection in faith.",
    reciter: "minshawi",
  },
  {
    id: "yusuf-die-muslim",
    category: "family",
    title: "Duʿā of Yūsuf at the height of success",
    surah: 12, start: 101, end: 101,
    intents: ["after great success","peak of career","summit moment","cause me to die a muslim","dont let success ruin me","gratitude at the top"],
    context: "Yūsuf ﷺ, now ruler of Egypt, prayed: 'Cause me to die a Muslim and join me with the righteous.'",
    reciter: "alafasy",
  },

  // ─── PARENTS ──────────────────────────────────────────────────────────────
  {
    id: "isra-parents",
    category: "parents",
    title: "Mercy upon parents — as they raised me small",
    surah: 17, start: 23, end: 24,
    intents: ["my parents","mother","father","old age of parents","caring for parents","parents passed away","filial love","birr al-walidayn","mercy upon mom and dad"],
    context: "'And lower to them the wing of humility out of mercy, and say: My Lord, have mercy upon them as they brought me up [when I was] small.'",
    reciter: "alafasy",
  },
  {
    id: "ibrahim-forgive-parents",
    category: "parents",
    title: "Forgiveness for parents on Reckoning Day",
    surah: 14, start: 41, end: 41,
    intents: ["parents on judgement day","forgive my parents and me","intercede for parents","duʿā for late parents"],
    context: "'Our Lord, forgive me and my parents and the believers on the Day the account is established.'",
    reciter: "minshawi",
  },
  {
    id: "nuh-parents-house",
    category: "parents",
    title: "Comprehensive duʿā for self, parents, household",
    surah: 71, start: 28, end: 28,
    intents: ["family forgiveness","whole household","everyone who enters my home","comprehensive household duʿā"],
    context: "Nūḥ ﷺ included parents, household, and the wider community of believers.",
    reciter: "minshawi",
  },

  // ─── KNOWLEDGE & WISDOM ───────────────────────────────────────────────────
  {
    id: "taha-knowledge",
    category: "knowledge",
    title: "Increase me in knowledge",
    surah: 20, start: 114, end: 114,
    intents: ["seeking knowledge","studying","exam","research","understanding","clarity","increase my ilm","more wisdom","want to learn"],
    context: "The only thing Allah told the Prophet ﷺ to ask for an increase of: 'My Lord, increase me in knowledge.'",
    reciter: "husary",
  },
  {
    id: "shuara-wisdom",
    category: "knowledge",
    title: "Duʿā of Ibrāhīm for wisdom and righteous company",
    surah: 26, start: 83, end: 85,
    intents: ["wisdom","good company","righteous friends","find good people","truthful tongue","leave a legacy","be remembered well"],
    context: "Ibrāhīm ﷺ asked for wisdom (ḥukm), to be joined with the righteous, and for an honorable mention among later generations.",
    reciter: "abdulbasit",
  },
  {
    id: "naml-grateful",
    category: "knowledge",
    title: "Duʿā of Sulaymān — gratitude for blessings",
    surah: 27, start: 19, end: 19,
    intents: ["gratitude for parents","gratitude for blessings","grateful for what allah gave me","do good with my gifts","use my talents well"],
    context: "Sulaymān ﷺ, on hearing the ant: 'My Lord, enable me to be grateful for Your favor that You bestowed upon me and upon my parents, and to do righteousness of which You approve.'",
    reciter: "alafasy",
  },

  // ─── TRAVEL ───────────────────────────────────────────────────────────────
  {
    id: "zukhruf-mounts",
    category: "travel",
    title: "Duʿā of mounting a vehicle",
    surah: 43, start: 13, end: 14,
    intents: ["travel","driving","flying","car","plane","journey","road trip","leaving on a trip","safe travel"],
    context: "Recited when boarding any conveyance: 'Glory to Him who has subjected this to us, and we could not have done it ourselves; and indeed to our Lord we will return.'",
    reciter: "alafasy",
  },
  {
    id: "muminun-disembark",
    category: "travel",
    title: "Duʿā of disembarking — Nūḥ on the ark",
    surah: 23, start: 28, end: 29,
    intents: ["arriving at destination","getting off a flight","entering a city","new place","blessed landing","arrival duʿā"],
    context: "Nūḥ ﷺ said as the ark settled: 'My Lord, let me disembark at a blessed landing place, and You are the best to accommodate.'",
    reciter: "alafasy",
  },
  {
    id: "isra-entry-exit",
    category: "travel",
    title: "Sound entry, sound exit, helping authority",
    surah: 17, start: 80, end: 80,
    intents: ["new job","new home","starting a project","leaving a place","need a helper","relocation","big change","entering a difficult situation"],
    context: "'My Lord, cause me to enter a sound entrance and to exit a sound exit, and grant me from Yourself a supporting authority.'",
    reciter: "husary",
  },

  // ─── HEREAFTER & DEATH ────────────────────────────────────────────────────
  {
    id: "imran-not-aimless",
    category: "hereafter",
    title: "You did not create this aimlessly",
    surah: 3, start: 191, end: 194,
    intents: ["meaning of life","purpose","why am i here","reflect on creation","standing at night","tahajjud","prepare for hereafter","awe at the universe"],
    context: "The closing four verses of Āl ʿImrān — recited by the Prophet ﷺ as he wept through the night.",
    reciter: "abdulbasit",
  },
  {
    id: "al-mulk",
    category: "hereafter",
    title: "Sūrat al-Mulk — protection in the grave",
    surah: 67, start: 1, end: 30,
    intents: ["before sleep","grave protection","intercession surah","nightly recitation","fear of grave","barzakh"],
    context: "The Prophet ﷺ would not sleep until he recited al-Mulk and as-Sajdah. It intercedes for its reciter until they are forgiven.",
    hadith: "There is a sūrah in the Qur'an, only thirty verses, that interceded for a man until he was forgiven: tabārakal-ladhī biyadihi-l-mulk. (Tirmidhī, Abū Dāwūd)",
    reciter: "alafasy",
  },
  {
    id: "baqarah-best",
    category: "hereafter",
    title: "Good in this world and the next",
    surah: 2, start: 201, end: 201,
    intents: ["best of both worlds","success in dunya and akhirah","comprehensive duʿā","general blessing","balance"],
    context: "The most popular du'ā of all — known to every Muslim child. Said in tawāf, in sajdah, anywhere.",
    reciter: "alafasy",
  },
  {
    id: "muminun-not-with-wrongdoers",
    category: "hereafter",
    title: "Do not place me among the wrongdoing people",
    surah: 23, start: 93, end: 94,
    intents: ["dont let me die among bad company","good companions at death","keep me with the righteous","fear of bad end"],
    context: "'My Lord, if You should show me that which they are promised — my Lord, do not place me among the wrongdoing people.'",
    reciter: "alafasy",
  },

  // ─── VICTORY OVER ENEMIES / OPPRESSION ────────────────────────────────────
  {
    id: "baqarah-jalut",
    category: "victory",
    title: "Patience, firm feet, and victory — Ṭālūt's army",
    surah: 2, start: 250, end: 250,
    intents: ["facing oppression","under siege","outnumbered","hopeless cause","need backbone","stand against tyranny","palestine","oppressed peoples"],
    context: "Said by the believers with Ṭālūt facing Goliath: 'Our Lord, pour upon us patience, plant firmly our feet, and give us victory over the disbelieving people.'",
    reciter: "sudais",
  },
  {
    id: "mumtahanah-not-trial",
    category: "victory",
    title: "Do not make us a trial for the disbelievers",
    surah: 60, start: 4, end: 5,
    intents: ["dont let oppressors mock us","muslim community under siege","spare us from being broken","dignified in trial"],
    context: "From the example of Ibrāhīm ﷺ: 'Our Lord, do not make us [objects of] torment for the disbelievers, and forgive us, our Lord.'",
    reciter: "sudais",
  },
  {
    id: "asiya-rescue",
    category: "victory",
    title: "Āsiyah — save me from Pharaoh",
    surah: 66, start: 11, end: 11,
    intents: ["oppressive ruler","escape tyranny","rescue from injustice","rescue from a ruler","save me from this regime"],
    context: "The wife of Pharaoh asking, while in the palace of the worst tyrant, for liberation and a house in Paradise.",
    reciter: "minshawi",
  },

  // ─── HEALING ──────────────────────────────────────────────────────────────
  {
    id: "ayyub-illness",
    category: "healing",
    title: "Duʿā of Ayyūb — illness and Allah's mercy",
    surah: 21, start: 83, end: 84,
    intents: ["illness","disease","cancer","chronic illness","healing","sickness","i am ill","my body is failing","seeking shifa","loved one is sick"],
    context: "'Indeed, adversity has touched me, and You are the most merciful of the merciful.' Allah removed his affliction and restored him.",
    reciter: "minshawi",
  },
  {
    id: "shuara-cures",
    category: "healing",
    title: "When I am ill, He cures me",
    surah: 26, start: 78, end: 82,
    intents: ["affirm allah heals","trust the cure","before surgery","accept treatment","faith in healing","cure for illness"],
    context: "Ibrāhīm ﷺ describing his Lord: 'And when I am ill, it is He who cures me.'",
    reciter: "abdulbasit",
  },
  {
    id: "isra-healing-quran",
    category: "healing",
    title: "The Qur'an as healing and mercy",
    surah: 17, start: 82, end: 82,
    intents: ["spiritual healing","ruqya","read for shifa","heart needs healing","quran as cure","emotional healing"],
    context: "'And We send down of the Qur'an that which is a healing and a mercy to the believers.' Foundation verse for ruqyah.",
    reciter: "abdulbasit",
  },
  {
    id: "fussilat-healing",
    category: "healing",
    title: "Guidance and healing for the believers",
    surah: 41, start: 44, end: 44,
    intents: ["spiritual cure","heart disease","need clarity and healing","guidance in confusion"],
    context: "'For those who believe, it is guidance and healing.'",
    reciter: "husary",
  },

  // ─── GRATITUDE ────────────────────────────────────────────────────────────
  {
    id: "naml-grateful-2",
    category: "gratitude",
    title: "Enable me to be grateful",
    surah: 27, start: 19, end: 19,
    intents: ["thankful","grateful","alhamdulillah","good news","received a gift","celebration","milestone","want to be grateful"],
    context: "Sulaymān ﷺ smiled at the ant and turned to gratitude immediately.",
    reciter: "alafasy",
  },
  {
    id: "ibrahim-grateful",
    category: "gratitude",
    title: "Praise be to Allah who granted me — in old age",
    surah: 14, start: 39, end: 39,
    intents: ["grateful for late blessings","thanks for unexpected gift","late in life mercy","never gave up"],
    context: "Ibrāhīm ﷺ in old age: 'Praise be to Allah, who has granted me in old age Ismāʿīl and Isḥāq.'",
    reciter: "abdulbasit",
  },

  // ─── GENERAL / DAILY ──────────────────────────────────────────────────────
  {
    id: "ali-imran-witness-tawhid",
    category: "general",
    title: "Allah witnesses there is no god but He",
    surah: 3, start: 18, end: 19,
    intents: ["affirm tawhid","monotheism","strengthen iman","central declaration","daily affirmation"],
    context: "Allah, His angels, and those of knowledge witness oneness — recited as a profound daily anchor.",
    reciter: "abdulbasit",
  },
  {
    id: "ali-imran-king",
    category: "general",
    title: "Owner of dominion — give and take",
    surah: 3, start: 26, end: 27,
    intents: ["seeking honor","losing status","need dignity","feel humiliated","trust the giver","change of fortune","unfairly dismissed"],
    context: "'Say: O Allah, Owner of all sovereignty, You give the kingdom to whom You will and take it from whom You will.'",
    reciter: "sudais",
  },
  {
    id: "ikhlas",
    category: "general",
    title: "Sūrat al-Ikhlāṣ — equal to a third of the Qur'an",
    surah: 112, start: 1, end: 4,
    intents: ["affirm tawhid","quick recitation","cant read much","short surah","third of the quran","tahara of belief"],
    context: "Recited three times equals the reward of the entire Qur'an. The pure declaration of God's oneness.",
    hadith: "It is equal to a third of the Qur'an. (Bukhārī, Muslim)",
    reciter: "alafasy",
  },
  {
    id: "naas-falaq-ikhlas",
    category: "general",
    title: "The three Quls — morning and evening",
    surah: 112, start: 1, end: 4,
    intents: ["morning adhkar","evening adhkar","daily protection","three quls","sunnah routine"],
    context: "Recited three times each in morning and evening as comprehensive protection.",
    reciter: "alafasy",
  },
  {
    id: "rahman",
    category: "general",
    title: "Sūrat ar-Raḥmān — the Bride of the Qur'an",
    surah: 55, start: 1, end: 78,
    intents: ["awe","reflect on blessings","which favors","beauty of creation","need to be moved","contemplation","gratitude reset"],
    context: "Each refrain — 'so which of the favors of your Lord will you deny?' — repeated 31 times. The Prophet ﷺ called it the Bride of the Qur'an.",
    reciter: "sudais",
  },
  {
    id: "yaseen",
    category: "general",
    title: "Sūrat Yā-Sīn — the heart of the Qur'an",
    surah: 36, start: 1, end: 83,
    intents: ["heart of the quran","ease of affairs","comprehensive duʿā","need general help","loved one passing","read at deathbed"],
    context: "Called the heart of the Qur'an. Traditionally recited for ease in matters and at the bedside of the dying.",
    reciter: "abdulbasit",
  },
];

/** Index categories for browse UI. */
export const DUA_CATEGORIES: { id: DuaCategory; title: string; emoji: string }[] = [
  { id: "hardship",    title: "Relief from hardship",        emoji: "🌧️" },
  { id: "wish",        title: "Wishes & specific needs",     emoji: "🤲" },
  { id: "provision",   title: "Provision & sustenance",      emoji: "🌾" },
  { id: "protection",  title: "Protection from harm",        emoji: "🛡️" },
  { id: "forgiveness", title: "Forgiveness & repentance",    emoji: "🌿" },
  { id: "guidance",    title: "Guidance & steadfastness",    emoji: "🧭" },
  { id: "anxiety",     title: "Anxiety & fear",              emoji: "🕊️" },
  { id: "family",      title: "Spouse & children",           emoji: "👨‍👩‍👧" },
  { id: "parents",     title: "Parents",                     emoji: "🤱" },
  { id: "knowledge",   title: "Knowledge & wisdom",          emoji: "📖" },
  { id: "travel",      title: "Travel",                      emoji: "✈️" },
  { id: "hereafter",   title: "Death & the Hereafter",       emoji: "🌙" },
  { id: "victory",     title: "Victory over oppression",     emoji: "⚔️" },
  { id: "healing",     title: "Healing",                     emoji: "🌸" },
  { id: "gratitude",   title: "Gratitude",                   emoji: "✨" },
  { id: "general",     title: "Daily & general",             emoji: "🕌" },
];
